#!/bin/bash
# ==============================================================================
# 🔍 DEEP FORENSIC AUDIT: MOCK DATA POISONING IDENTIFICATION
# ==============================================================================

TARGET_FILE="data/testing-input-output/tuning_main/inputs-outputs/cube_50-50-50.step"

echo "========================================================================"
echo "🔎 HUNTER: Finding the code that injects 'Mock CAD/Step Data'"
echo "========================================================================"
# Search for the mock string in the entire repository to find the culprit script
grep -rn "Mock CAD" . || echo "❌ Mock string not found in source code (possibly generated by binary/env)"

echo -e "\n========================================================================"
echo "🔎 SMOKING GUN: Source Audit (The file content is wrong!)"
echo "========================================================================"
if [ -f "$TARGET_FILE" ]; then
    cat -n "$TARGET_FILE"
else
    echo "❌ ERROR: Target file not found."
fi

echo -e "\n========================================================================"
echo "🔧 AUTOMATED REPAIRS & RECOVERY"
echo "========================================================================"
echo "If the file is poisoned, use these to force-correct it:"

# Strategy: If the file is just the mock string, overwrite it with the real valid schema
# # echo -e "ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('FreeCAD Model'),'2;1');\nFILE_NAME('Open CASCADE Shape Model','2026-06-29',('Author'),(''),'','','');\nFILE_SCHEMA(('AUTOMOTIVE_DESIGN_CC2'));\nENDSEC;\nDATA;\nENDSEC;\nEND-ISO-10303-21;" > "$TARGET_FILE"

# Strategy: If you want to rename/move the real file from your tests/dummies folder to the tuning folder
# # cp data/testing-input-output/repositories/mesh_generator/tests/dummies/sample_geometry.step "$TARGET_FILE"

# Strategy: If you suspect windows line endings, run this (uncomment if needed)
# # sed -i 's/\r$//' "$TARGET_FILE"

# Strategy: If you have a specific pattern to remove, use this (uncomment if needed)
# # sed -i '/Mock CAD/d' "$TARGET_FILE"

echo "========================================================================"
echo "🏁 FORENSIC AUDIT COMPLETE"
echo "========================================================================"