name: "🛰️ Simulators Pipeline Tuning Pulse (Beta)"

on:
  schedule:
    # Runs at the 29th minute of every hour
    - cron: "29 * * * *"

jobs:
  tuner:
    uses: ./.github/workflows/tuner_core.yml
    secrets: inherit