name: "🛰️ Simulators Pipeline Tuning Pulse (Beta)"

# This keeps the workflow valid and inactive, but allows manual triggering
on:
  workflow_dispatch: {}

# on:
#   schedule:
#     # Runs at the 29th minute of every hour
#     - cron: "29 * * * *"

jobs:
  tuner:
    uses: ./.github/workflows/tuner_core.yml
    secrets: inherit