name: "🛰️ Simulators Pipeline Tuning Pulse (Alpha)"

# on:
#   schedule:
#     # Runs at the 14th minute of every hour
#     - cron: "14 * * * *"

jobs:
  tuner:
    uses: ./.github/workflows/tuner_core.yml
    secrets: inherit